### ISSUE TITLE
Folder for BD?

### ISSUE THREAD

**Issue by Raart** [sblask/firefox-bookmark-dial#1]
Hi sblask. I'm using BD for 5 months now with no problems. 
Then, after autoupdating FF to v45.0.1, BD v1.1.2 shows a black screen on opening a new tab.
So I've tried to "Choose a folder..." by right clicking on the black tab with no success. 
A white blank form "_Choose a folder for Bookmark Dial:_" appears with no possibility to select the folder.
Same result obtained by pressing the "Choose" button in Options from the Extensions tab.
At this point I've tried disabling all extensions but BD. 
Even after a FF restart nothing changes.
Next I've reinstalled BD from the add-ons site (and restarted FF). 
No changes. The folder can't be specified.
Any suggestion?

**Comment by sblask** [comment]
I am on 45.0.1 and it works fine for me. You could try installing bookmark dial creating a new profile (https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) Assuming you use sync, it will be easy to get your data and settings to the new profile, but at first just try whether it works, don't delete your current profile. You can also check `browser console` and `web console` from the `developer` menu. See whether there is some kind of exception...

**Comment by sblask** [comment]
Closing this as I did not get more information.
