### ISSUE TITLE
Pages using HTTP Basic Access Authentication pop up login dialog periodically

### ISSUE THREAD

**Issue by fritzophrenic** [sblask/firefox-bookmark-dial#2]
I assume this happens because Bookmark Dial loads pages in a background tab to refresh the thumbnails.

I have a few pages in my chosen bookmarks folder that require HTTP authentication to load the page.

Every now and then Bookmark Dial decides to refresh those thumbnails and I am forced to re-enter my login credentials. This is very distracting because I'm usually browsing another page entirely.

Best case would be to detect that the HTTP Auth login is required, and skip updating the thumbnail for that page (just using the old one) unless the user explicitly requests to refresh the thumbnail (or there is no thumbnail yet).

A good workaround could be to be able to mark certain thumbnails to prevent them from automatically updated.

**Comment by sblask** [comment]
I can see how this is very annoying. Unfortunately there is currently no future proof API that I could use to detect such a situation and I am actually not very interested in adding more functionality to this add-on given that the future of the APIs I use is very unclear. I will probably just move to Vivaldi at some point where speed dial functionality (alongside many other things that I consider basic) is built-in. You could try this as a workaround: https://en.wikipedia.org/wiki/Basic_access_authentication#URL_encoding
