### ISSUE TITLE
Folder / tab support

### ISSUE THREAD

**Issue by RL79** [sblask/firefox-bookmark-dial#3]
Hi,

Maybe I overlooked it but I would love to see support for (sub) folders. Possibly display them as tabs in the speeddial.
Or alternatively, tabs and each tab its own destination folder.

**Comment by sblask** [comment]
I don't see the point. If you want full navigation in bookmarks, the sidebar is much more suitable. Bookmark Dial is meant to provide quick access to a bunch of bookmarks when opening a new tab.
