### ISSUE TITLE
Settable Refresh Rate

### ISSUE THREAD

**Issue by momrpg** [sblask/firefox-bookmark-dial#5]
Hi there!  Is there a way we can add a user-configurable refresh rate for the thumbs?

**Comment by sblask** [comment]
It's possible, but I don't want to and don't currently have the time anyway. The way it is done now is that thumbnails are generated when they don't exist and at least one bookmark dial page is open. The idea was to no have resource intense stuff going on if there is no indication of where it could come from. I have seen pages that killed my Firefox and I would not want that to happen in the background and no way to stop it. The other issue is that I use a few things that are not multiprocessing compatible and I didn't find a workaround when I was working on it. Porting to webextensions would be a lot of work and I am not even sure it could be done.
