### ISSUE TITLE
Background color picker

### ISSUE THREAD

**Issue by anewuser** [sblask/firefox-bookmark-dial#7]
Supporting images and CSS is nice, but I suggest you to let people pick a color as their background too.

Also, the default black background may be discouraging to non-technical users. You could change it to a grey tone.

**Comment by sblask** [comment]
There are addons like this: https://addons.mozilla.org/en-US/firefox/addon/color-that-site/ that can do what you want. I believe in simplicity and if I'd started to implement something like this, there would be no end and a lot of effort to maintain. Negative example for me is the Fast Dial extension that had a lot of styling functionality but only half of it worked.
